# Generated by Django 3.0.4 on 2020-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('hash_field', models.CharField(db_column='hash_', max_length=300, primary_key=True, serialize=False)),
                ('timestamp_field', models.IntegerField(blank=True, db_column='timestamp_', null=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=300, null=True)),
                ('destination', models.CharField(blank=True, max_length=300, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions_eth',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('address', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('eth_balance', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'utilisateur_eth',
                'managed': True,
            },
        ),
    ]
