# Generated by Django 3.0.4 on 2020-04-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('adresse', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nb_tx', models.IntegerField(blank=True, null=True)),
                ('total_recu', models.FloatField(blank=True, null=True)),
                ('total_envoye', models.FloatField(blank=True, null=True)),
                ('solde_final', models.FloatField(blank=True, null=True)),
                ('nb_bcalcules', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('hash_tx', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('hauteur', models.IntegerField(blank=True, null=True)),
                ('adresse', models.ForeignKey(blank=True, db_column='adresse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bitcoin.Utilisateur')),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('hauteur', models.IntegerField(primary_key=True, serialize=False)),
                ('hash_bloc', models.CharField(blank=True, max_length=100, null=True)),
                ('nb_tx', models.IntegerField(blank=True, null=True)),
                ('adresse', models.ForeignKey(blank=True, db_column='adresse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bitcoin.Utilisateur')),
            ],
            options={
                'db_table': 'bloc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('adresse', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valeur_i', models.FloatField()),
                ('date', models.IntegerField()),
                ('hash_tx', models.ForeignKey(db_column='hash_tx', on_delete=django.db.models.deletion.DO_NOTHING, to='bitcoin.Transactions')),
            ],
            options={
                'db_table': 'outputs',
                'managed': True,
                'unique_together': {('adresse', 'valeur_i', 'hash_tx', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('adresse', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valeur_i', models.FloatField()),
                ('date', models.IntegerField()),
                ('hash_tx', models.ForeignKey(db_column='hash_tx', on_delete=django.db.models.deletion.DO_NOTHING, to='bitcoin.Transactions')),
            ],
            options={
                'db_table': 'inputs',
                'managed': True,
                'unique_together': {('adresse', 'valeur_i', 'hash_tx', 'date')},
            },
        ),
    ]
